// Lines shown at random on the blocked page. Edit freely.
const BLOCKED_LINES = [
    'You will die.',
    'This is your one life.',
    'Time you can\'t get back.',
    'Still worth it?',
    'You\'ll never get this moment again.',
    'You got shit to do.',
    'Dont waste your time idiot',
    'Have you condidered going on an adventure instead of doom scrolling',
    'Nobody is coming to save the time you waste here.',
    'You are not tired. You are numb.',
    'This is what avoidance looks like.',
    'The scroll never ends because it was built not to.',
    'You will not remember a single second of this tomorrow.',
    'Somewhere, the version of you that you want to become is waiting.',
    'This is a rehearsal for the rest of your life. Act like it.',
    'Comfort is the slow death of ambition.',
    'You are trading years for minutes.',
    'Nobody on their deathbed asks for more screen time.',
    'The algorithm does not care if you become who you could be.',
    'You already know this isn\'t it.',
    'Discipline is choosing between what you want now and what you want most.',
    'You are one decision away from a different life. This isn\'t it.',
    'Boredom is not an emergency. Stop treating it like one.',
    'The person you\'re avoiding becoming is watching.',
    'This feeling you\'re avoiding will still be there after.',
    'You cannot scroll your way out of the life you\'re building.',
    'Every minute here is a vote for the person you don\'t want to be.',
    'You will not be remembered for the hours you spent here.',
    'The work is still waiting. It will not do itself.',
    'You are dying slowly, and this is how you\'re spending it.',
    'No one is impressed by how long you can stare at a screen.',
    'This is the opposite of the life you say you want.',
    'You already regret this before you\'ve even started.',
    'The clock does not pause because you\'re bored.',
    'What would you tell someone else doing exactly this?',
    'This is not rest. Rest restores you. This empties you.',
    'You are one click from wasting an hour you\'ll never get back.',
    'The distraction is the point. Someone profits from your attention.',
    'You were made for more than this feed.',
    'Close this. Go be someone.',
];

// Drop image files into images/, then list their filenames here.
const BLOCKED_IMAGES = [
  '03fdc619a4492c0c6f2efdf95a276e11.jpg',
  '1a3dd90ba2515c10d4f2a687f30c950e.jpg',
  '77a8aab9dd30e204fb1ca8fac38d87c5.jpg',
  '8e7e6b4a54602506a533b344900b5b75.jpg',
  'MV5BNTY1MzgzOTYxNV5BMl5BanBnXkFtZTgwMDI4OTEwMjE@._V1_.jpg',
  'Marcus-Aurelius-statue-Rome-Piazza-del-Campidoglio.webp',
  'Yoda.webp',
  'cbeb47fcf1c6934747b9e396a4ea7d8f.jpg',
  'ee977f625baa37c9878fad37b89d1b10.jpg',
];
